# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='image',
            field=models.FileField(default='images/no-img.jpg', upload_to='images/'),
        ),
    ]
